[workspace]
authors = ["JHIH-SIOU LI <jsli@linux.com>"]
channels = ["conda-forge"]
name = "toy-transformer"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
cuda = "12.8.*"
cuda-toolkit = ">=12.8.1,<13"
python = "3.12.*"

[pypi-dependencies]
torch = "==2.7.1"
